# Generated by Django 2.1.4 on 2019-02-18 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181208_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agent_promo_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
