# Generated by Django 2.1.4 on 2019-03-05 06:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cgx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Patient Name')),
                ('promo_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Promo Code')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date of Birth')),
                ('state', models.CharField(blank=True, max_length=250, null=True, verbose_name='State')),
                ('test', models.CharField(blank=True, max_length=250, null=True, verbose_name='Test')),
                ('active_inactive', models.CharField(blank=True, max_length=250, null=True, verbose_name='Active/Inactive')),
                ('status', models.CharField(blank=True, max_length=150, null=True, verbose_name='Status')),
                ('insurance_status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Insurance Status')),
                ('policy_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Policy Number')),
                ('verification_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('deductible_remainding', models.CharField(blank=True, max_length=250, null=True, verbose_name='Deductible Remainding')),
                ('notes', models.TextField(blank=True, null=True)),
                ('patient_id_photo', models.ImageField(blank=True, max_length=1000, null=True, upload_to='insurance/patient-id-photo/')),
                ('insurance_card_photo_front', models.ImageField(blank=True, max_length=1000, null=True, upload_to='insurance/insurance-card-photo-front/')),
                ('insurance_card_photo_back', models.ImageField(blank=True, max_length=1000, null=True, upload_to='insurance/insurance-card-photo-back/')),
                ('additional_insurance_cards', models.ImageField(blank=True, max_length=1000, null=True, upload_to='insurance/additional-insurance-cards/')),
                ('consent_recording', models.FileField(blank=True, max_length=1000, null=True, upload_to='insurance/consent_recording/')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.today, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user_promo_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Promo code of the agent who created this record.')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Agent', verbose_name='Agent name')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Manager', verbose_name='Manager Name')),
            ],
            options={
                'verbose_name_plural': 'Insurance records',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfInsurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Name of the Insurance')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='insurance',
            name='type_of_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance.TypeOfInsurance', verbose_name='Type of Insurance'),
        ),
    ]
