# Generated by Django 2.1.4 on 2018-12-15 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cgx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Completed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Patient Name')),
                ('promo_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Promo Code')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Date of Birth')),
                ('state', models.CharField(blank=True, max_length=250, null=True, verbose_name='State')),
                ('test', models.CharField(blank=True, max_length=250, null=True, verbose_name='Test')),
                ('active_inactive', models.CharField(blank=True, max_length=250, null=True, verbose_name='Active/Inactive')),
                ('status', models.CharField(blank=True, max_length=150, null=True, verbose_name='Status')),
                ('policy_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Policy Number')),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('deductible_remainding', models.CharField(blank=True, max_length=250, null=True, verbose_name='Deductible Remainding')),
                ('notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Agent', verbose_name='Agent name')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Manager', verbose_name='Manager Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Patient Name')),
                ('promo_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Promo Code')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Date of Birth')),
                ('state', models.CharField(blank=True, max_length=250, null=True, verbose_name='State')),
                ('test', models.CharField(blank=True, max_length=250, null=True, verbose_name='Test')),
                ('active_inactive', models.CharField(blank=True, max_length=250, null=True, verbose_name='Active/Inactive')),
                ('status', models.CharField(blank=True, max_length=150, null=True, verbose_name='Status')),
                ('policy_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Policy Number')),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('deductible_remainding', models.CharField(blank=True, max_length=250, null=True, verbose_name='Deductible Remainding')),
                ('notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Agent', verbose_name='Agent name')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Manager', verbose_name='Manager Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pending',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Patient Name')),
                ('promo_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Promo Code')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Date of Birth')),
                ('state', models.CharField(blank=True, max_length=250, null=True, verbose_name='State')),
                ('test', models.CharField(blank=True, max_length=250, null=True, verbose_name='Test')),
                ('active_inactive', models.CharField(blank=True, max_length=250, null=True, verbose_name='Active/Inactive')),
                ('status', models.CharField(blank=True, max_length=150, null=True, verbose_name='Status')),
                ('policy_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Policy Number')),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('deductible_remainding', models.CharField(blank=True, max_length=250, null=True, verbose_name='Deductible Remainding')),
                ('notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Agent', verbose_name='Agent name')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Manager', verbose_name='Manager Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Patient Name')),
                ('promo_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Promo Code')),
                ('date_of_birth', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Date of Birth')),
                ('state', models.CharField(blank=True, max_length=250, null=True, verbose_name='State')),
                ('test', models.CharField(blank=True, max_length=250, null=True, verbose_name='Test')),
                ('active_inactive', models.CharField(blank=True, max_length=250, null=True, verbose_name='Active/Inactive')),
                ('status', models.CharField(blank=True, max_length=150, null=True, verbose_name='Status')),
                ('policy_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Policy Number')),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('deductible_remainding', models.CharField(blank=True, max_length=250, null=True, verbose_name='Deductible Remainding')),
                ('notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Agent', verbose_name='Agent name')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Manager', verbose_name='Manager Name')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TypeOfInsurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Name of the Insurance')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rejected',
            name='type_of_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance.TypeOfInsurance', verbose_name='Type of Insurance'),
        ),
        migrations.AddField(
            model_name='pending',
            name='type_of_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance.TypeOfInsurance', verbose_name='Type of Insurance'),
        ),
        migrations.AddField(
            model_name='hold',
            name='type_of_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance.TypeOfInsurance', verbose_name='Type of Insurance'),
        ),
        migrations.AddField(
            model_name='completed',
            name='type_of_insurance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance.TypeOfInsurance', verbose_name='Type of Insurance'),
        ),
    ]
