# Generated by Django 2.1.4 on 2018-12-17 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completed',
            options={'ordering': ['name'], 'verbose_name_plural': 'Completed insurance records'},
        ),
        migrations.AlterModelOptions(
            name='hold',
            options={'ordering': ['name'], 'verbose_name_plural': 'Hold insurance records'},
        ),
        migrations.AlterModelOptions(
            name='pending',
            options={'ordering': ['name'], 'verbose_name_plural': 'Pending insurance records'},
        ),
        migrations.AlterModelOptions(
            name='rejected',
            options={'ordering': ['name'], 'verbose_name': 'Rejected insurance records'},
        ),
        migrations.AlterField(
            model_name='completed',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 17), null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='hold',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 17), null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='pending',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 17), null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='rejected',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 17), null=True, verbose_name='Date of Birth'),
        ),
    ]
