# Generated by Django 2.1.4 on 2018-12-18 11:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0003_auto_20181218_1139'),
        ('insurance', '0002_auto_20181217_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250, verbose_name='Patient Name')),
                ('promo_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Promo Code')),
                ('date_of_birth', models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of Birth')),
                ('state', models.CharField(blank=True, max_length=250, null=True, verbose_name='State')),
                ('test', models.CharField(blank=True, max_length=250, null=True, verbose_name='Test')),
                ('active_inactive', models.CharField(blank=True, max_length=250, null=True, verbose_name='Active/Inactive')),
                ('status', models.CharField(blank=True, max_length=150, null=True, verbose_name='Status')),
                ('insurance_status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Insurance Status')),
                ('policy_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Policy Number')),
                ('verification_date', models.DateField(blank=True, null=True)),
                ('deductible_remainding', models.CharField(blank=True, max_length=250, null=True, verbose_name='Deductible Remainding')),
                ('notes', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Agent', verbose_name='Agent name')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Manager', verbose_name='Manager Name')),
                ('type_of_insurance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='insurance.TypeOfInsurance', verbose_name='Type of Insurance')),
            ],
            options={
                'verbose_name_plural': 'Insurance records',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='completed',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='completed',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='completed',
            name='type_of_insurance',
        ),
        migrations.RemoveField(
            model_name='hold',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='hold',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='hold',
            name='type_of_insurance',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='pending',
            name='type_of_insurance',
        ),
        migrations.RemoveField(
            model_name='rejected',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='rejected',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='rejected',
            name='type_of_insurance',
        ),
        migrations.DeleteModel(
            name='Completed',
        ),
        migrations.DeleteModel(
            name='Hold',
        ),
        migrations.DeleteModel(
            name='Pending',
        ),
        migrations.DeleteModel(
            name='Rejected',
        ),
    ]
