# Generated by Django 2.1.5 on 2019-01-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_auto_20181218_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='for_insurance',
            field=models.BooleanField(default=0, verbose_name='For Insurance?'),
        ),
    ]
