# Generated by Django 2.1.5 on 2019-01-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_insurance_for_insurance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='for_insurance',
        ),
    ]
