# Generated by Django 2.1.4 on 2019-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_remove_insurance_for_insurance'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurance',
            name='additional_insurance_cards',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='insurance/additional-insurance-cards/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance_card_photo_back',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='insurance/insurance-card-photo-back/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='insurance_card_photo_front',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='insurance/insurance-card-photo-front/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='insurance',
            name='patient_id_photo',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='insurance/patient-id-photo/%Y/%m/%d'),
        ),
    ]
