# Generated by Django 2.1.4 on 2019-02-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0006_auto_20190201_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='additional_insurance_cards',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='insurance/additional-insurance-cards/'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_card_photo_back',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='insurance/insurance-card-photo-back/'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='insurance_card_photo_front',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='insurance/insurance-card-photo-front/'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='patient_id_photo',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='insurance/patient-id-photo/'),
        ),
    ]
