# Generated by Django 2.1.4 on 2019-02-02 07:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_insurance_consent_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='date_of_birth',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='insurance',
            name='verification_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
