# Generated by Django 2.1.5 on 2019-02-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0009_auto_20190202_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Patient Name'),
        ),
    ]
