# Generated by Django 2.1.4 on 2019-02-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0013_auto_20190224_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurance',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Patient Name'),
        ),
    ]
