# Generated by Django 2.1.4 on 2019-02-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paincreamandfootbath', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paincreamandfootbath',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paincreamandfootbath',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paincreamandfootbath',
            name='user_promo_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Promo code of the agent who created this record.'),
        ),
    ]
