# Generated by Django 2.1.4 on 2019-03-06 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paincreamandfootbath', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paincreamandfootbath',
            name='ppo_hmo_information_mem_id',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='PPO/HMO Information (If not straight Medicare)(Medicare ID#)'),
        ),
    ]
