# Generated by Django 2.1.4 on 2019-04-02 04:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('paincreamandfootbath', '0002_updated_not_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paincreamandfootbath',
            name='date_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
