# Generated by Django 2.1.4 on 2019-02-19 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paincreamandfootbath', '0002_auto_20190219_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='paincreamandfootbath',
            name='date_created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='paincreamandfootbath',
            name='discomfort',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='How long have you been experiencing discomfort?'),
        ),
        migrations.AlterField(
            model_name='paincreamandfootbath',
            name='feq_of_pain',
            field=models.CharField(blank=True, default='n/a', max_length=100, null=True, verbose_name='Frequency of pain'),
        ),
    ]
