# Generated by Django 2.1.4 on 2019-02-20 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paincreamandfootbath', '0003_auto_20190219_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paincreamandfootbath',
            options={'ordering': ['submission_date'], 'verbose_name': 'Pain Cream and Foot Bath', 'verbose_name_plural': 'Pain Cream and Foot Baths'},
        ),
    ]
