# Generated by Django 2.1.4 on 2018-12-15 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Agent id')),
                ('name', models.CharField(max_length=50, verbose_name='Agent name')),
            ],
        ),
        migrations.CreateModel(
            name='BioConfirmMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=250, verbose_name='Patient Name')),
                ('patient_phone_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Patient phone number')),
                ('promo_code', models.CharField(max_length=250, verbose_name='Promo Code')),
                ('date_app_rec', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Date application recorded')),
                ('date_sample_rec', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Date sample recorded')),
                ('type_of_test', models.IntegerField(blank=True, choices=[(1, 'CARRIER'), (2, 'CGX'), (3, 'CGX/CARRIER'), (4, 'L')], null=True, verbose_name='Test choices')),
                ('date_of_qca', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Date of QCA')),
                ('submitted_to_tamika_ins_verifier', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Date submitted to Tamika ins verifier')),
                ('telemed_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Telemed name')),
                ('date_submitted_to_telemed', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Date submitted to telemed')),
                ('date_telemed_returned', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Date telemed returned')),
                ('date_bioconfim_rec_app', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Date bioconfirm recorded application')),
                ('date_paid', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Date paid')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'CGX/CGD'), (2, 'DUPLICATE'), (3, 'HOLD'), (4, 'MISSING INFORMATION'), (5, 'REJECTED'), (6, 'WRONG APPLICATION'), (7, 'Resubmit from Elite'), (8, 'RESIGNED'), (10, 'REJECTED - HMO'), (11, 'REJECTED - NO ID'), (12, 'REJECTED - INELIGIBLE'), (13, 'REJECTED - INACTIVE'), (14, 'Higd ded 6680.37'), (15, 'REJECTED - CARESOURCE')], null=True, verbose_name='Status')),
                ('month', models.DateField(blank=True, null=True)),
                ('insurance_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Insurance company name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('rejection_date', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Rejection Date')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Agent', verbose_name='Agent name')),
            ],
            options={
                'ordering': ['patient_name'],
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Manager id')),
                ('name', models.CharField(max_length=50, verbose_name='Manager name')),
            ],
        ),
    ]
