# Generated by Django 2.1.4 on 2019-03-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='insurance_verified_tsg_verification',
            field=models.DateField(blank=True, null=True, verbose_name='Insurance Verified/TSG Verification'),
        ),
    ]
