# Generated by Django 2.1.4 on 2018-12-18 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0002_auto_20181217_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_app_rec',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date application recorded'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_bioconfim_rec_app',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date bioconfirm recorded application'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_of_qca',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date of QCA'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_paid',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date paid'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_sample_rec',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date sample recorded'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_submitted_to_telemed',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date submitted to telemed'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_telemed_returned',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date telemed returned'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='rejection_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Rejection Date'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='submitted_to_tamika_ins_verifier',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date submitted to Tamika ins verifier'),
        ),
    ]
