# Generated by Django 2.1.4 on 2018-12-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0003_auto_20181218_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={'ordering': ['name'], 'verbose_name': 'Agent name', 'verbose_name_plural': 'Agent names'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['name'], 'verbose_name': 'Manager name', 'verbose_name_plural': 'Manager names'},
        ),
    ]
