# Generated by Django 2.1.4 on 2019-01-03 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0004_auto_20181228_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Agent name'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Manager name'),
        ),
    ]
