# Generated by Django 2.1.4 on 2019-01-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0006_auto_20190121_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='status',
            field=models.IntegerField(blank=True, choices=[(1, 'CGX/CGD'), (2, 'DUPLICATE'), (3, 'HOLD'), (4, 'MISSING INFORMATION'), (5, 'REJECTED'), (6, 'WRONG APPLICATION'), (3, 'Requires Authorization'), (7, 'Resubmit from Elite'), (8, 'RESIGNED'), (10, 'REJECTED HMO'), (11, 'REJECTED - NO ID'), (12, 'REJECTED INELIGIBLE'), (13, 'REJECTED INACTIVE'), (14, 'REJECTED - Higd ded 6880.37'), (15, 'REJECTED CARESOURCE')], null=True, verbose_name='Status'),
        ),
    ]
