# Generated by Django 2.1.4 on 2019-01-21 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0009_auto_20190121_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
