# Generated by Django 2.1.5 on 2019-01-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0010_auto_20190121_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioconfirmmaster',
            name='for_bioconfirm',
            field=models.BooleanField(default=0, verbose_name='For Bio Confirm?'),
        ),
    ]
