# Generated by Django 2.1.4 on 2019-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0014_auto_20190129_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioconfirmmaster',
            name='additional_insurance_cards',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='bio-confirm-master/additional-insurance-cards/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='bioconfirmmaster',
            name='consent_recording',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='bio-confirm-master/consent-recording/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='bioconfirmmaster',
            name='insurance_card_photo_back',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='bio-confirm-master/insurance-card-photo-back/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='bioconfirmmaster',
            name='insurance_card_photo_front',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='bio-confirm-master/insurance-card-photo-front/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='bioconfirmmaster',
            name='patient_id_photo',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='bio-confirm-master/patient-id-photo/%Y/%m/%d'),
        ),
    ]
