# Generated by Django 2.1.4 on 2019-02-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0015_auto_20190201_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='additional_insurance_cards',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='bio-confirm-master/additional-insurance-cards/'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='consent_recording',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='bio-confirm-master/consent-recording/'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='insurance_card_photo_back',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='bio-confirm-master/insurance-card-photo-back/'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='insurance_card_photo_front',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='bio-confirm-master/insurance-card-photo-front/'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='patient_id_photo',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='bio-confirm-master/patient-id-photo/'),
        ),
    ]
