# Generated by Django 2.1.4 on 2019-02-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0016_auto_20190201_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bioconfirmmaster',
            options={'ordering': ['-patient_name']},
        ),
    ]
