# Generated by Django 2.1.5 on 2019-02-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0017_auto_20190202_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bioconfirmmaster',
            options={'ordering': ['patient_name']},
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='patient_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Patient Name'),
        ),
    ]
