# Generated by Django 2.1.4 on 2019-02-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0017_auto_20190202_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bioconfirmmaster',
            options={'ordering': ['patient_name']},
        ),
    ]
