# Generated by Django 2.1.5 on 2019-02-10 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0018_auto_20190210_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='promo_code',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Promo Code'),
        ),
    ]
