# Generated by Django 2.1.4 on 2019-02-18 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0021_bioconfirmmaster_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_created',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='user_promo_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Promo code of the agent who created this record.'),
        ),
    ]
