# Generated by Django 2.1.4 on 2019-02-18 12:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0022_auto_20190218_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_created',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
