# Generated by Django 2.1.4 on 2019-02-20 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0023_auto_20190218_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
