# Generated by Django 2.1.4 on 2019-02-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0024_agent_promo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='patient_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Patient Name'),
        ),
    ]
