# Generated by Django 2.1.4 on 2019-03-05 04:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0026_auto_20190224_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Status id')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Test_choices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Test choices id')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Test choice')),
            ],
            options={
                'verbose_name': 'Test Choice',
                'verbose_name_plural': 'Test Choices',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='bioconfirmmaster',
            name='submitted_to_tamika_ins_verifier',
        ),
        migrations.AddField(
            model_name='bioconfirmmaster',
            name='insurance_verified_tsg_verification',
            field=models.DateField(blank=True, null=True, verbose_name='INSURANCE VERIFIED/TSG VERIFICATION'),
        ),
        migrations.AddField(
            model_name='bioconfirmmaster',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Manager', verbose_name='Manager name'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_bioconfim_rec_app',
            field=models.DateField(blank=True, null=True, verbose_name='Date bioconfirm recorded application'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_of_qca',
            field=models.DateField(blank=True, null=True, verbose_name='Date of QCA'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_paid',
            field=models.DateField(blank=True, null=True, verbose_name='Date paid'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_sample_rec',
            field=models.DateField(blank=True, null=True, verbose_name='Date sample recorded'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_submitted_to_telemed',
            field=models.DateField(blank=True, null=True, verbose_name='Date submitted to telemed'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='date_telemed_returned',
            field=models.DateField(blank=True, null=True, verbose_name='Date telemed returned'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='rejection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rejection Date'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='status',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='bioconfirmmaster',
            name='type_of_test',
            field=models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Test_choices', verbose_name='Test choices'),
        ),
    ]
