# Generated by Django 2.1.4 on 2019-03-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgx', '0027_updates_on_dates_and_test_status_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioconfirmmaster',
            name='date_lab_recorded_app',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bioconfirmmaster',
            name='lab_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
