from rest_framework import serializers

from .models import Supply


class SuppliesSerializer(serializers.ModelSerializer):
    sale_rep_name = serializers.CharField(
        max_length=250, default='n/a', required=False)
    sale_rep_number = serializers.CharField(
        max_length=250, default='n/a', required=False)
    email = serializers.EmailField(max_length=100, required=False)
    shipping_labels_qty_req = serializers.CharField(
        max_length=250, default='n/a', required=False)
    shipping_labels_qty_auth = serializers.CharField(
        max_length=250, default='n/a', required=False)
    shipping_boxes_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    shipping_boxes_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    shipping_bags_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    shipping_bags_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    specimen_bags_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    specimen_bags_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    tox_cups_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    tox_cups_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    tox_req_forms_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    tox_req_forms_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    pgx_swabs_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    pgx_swabs_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    pgx_swabs_req_forms_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    pgx_swabs_req_forms_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    pgx_medical_necessity_forms_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    pgx_medical_necessity_forms_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    cgx_swabs_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    cgx_swabs_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    cgx_req_forms_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    cgx_req_forms_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    tubes_tiger_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    tubes_tiger_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    tubes_lavender_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    tubes_lavender_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    tubes_red_top_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    tubes_red_top_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    tubes_blue_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    tubes_blue_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    tubes_dark_blue_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    tubes_dark_blue_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    tubes_violet_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    tubes_violet_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    straight_needle_18_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    straight_needle_18_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    straight_needle_20_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    straight_needle_20_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    straight_needle_21_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    straight_needle_21_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    straight_needle_22_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    straight_needle_22_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    straight_needle_23_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    straight_needle_23_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    butterfly_needle_18_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    butterfly_needle_18_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    butterfly_needle_20_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    butterfly_needle_20_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    butterfly_needle_21_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    butterfly_needle_21_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    butterfly_needle_22_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    butterfly_needle_22_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    butterfly_needle_23_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    butterfly_needle_23_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    needle_vacuum_tubes_18_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    needle_vacuum_tubes_18_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    uti_cups_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    uti_cups_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    uti_urine_tubes_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    uti_urine_tubes_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    culture_swabs_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    culture_swabs_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    tourniquets_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    tourniquets_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    gauze_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    gauze_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    bandages_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    bandages_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)
    gel_pack_qty_req = serializers.CharField(max_length=250, default='n/a', required=False)
    gel_pack_qty_auth = serializers.CharField(max_length=250, default='n/a', required=False)

    class Meta:
        model = Supply
        fields = '__all__'
