# Generated by Django 2.1.4 on 2019-03-05 06:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cgx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_name', models.CharField(blank=True, max_length=250, null=True, unique=True, verbose_name='Patient Name')),
                ('patient_phone_number', models.CharField(blank=True, max_length=250, null=True, verbose_name='Patient phone number')),
                ('promo_code', models.CharField(blank=True, max_length=250, null=True, verbose_name='Promo Code')),
                ('date_app_rec', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Date application recorded')),
                ('date_sample_rec', models.DateField(blank=True, null=True, verbose_name='Date sample recorded')),
                ('date_of_qca', models.DateField(blank=True, null=True, verbose_name='Date of QCA')),
                ('insurance_verified_tsg_verification', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='INSURANCE VERIFIED/TSG VERIFICATION')),
                ('telemed_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Telemed name')),
                ('date_submitted_to_telemed', models.DateField(blank=True, null=True, verbose_name='Date submitted to telemed')),
                ('date_telemed_returned', models.DateField(blank=True, null=True, verbose_name='Date telemed returned')),
                ('date_bioconfim_rec_app', models.DateField(blank=True, null=True, verbose_name='Date bioconfirm recorded application')),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='Date paid')),
                ('date_lab_recorded_app', models.DateField(blank=True, null=True)),
                ('lab_type', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='State')),
                ('month', models.CharField(blank=True, max_length=50, null=True)),
                ('insurance_company', models.CharField(blank=True, max_length=50, null=True, verbose_name='Insurance company name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('rejection_date', models.DateField(blank=True, null=True, verbose_name='Rejection Date')),
                ('patient_id_photo', models.ImageField(blank=True, max_length=1000, null=True, upload_to='bio-confirm-master/patient-id-photo/')),
                ('insurance_card_photo_front', models.ImageField(blank=True, max_length=1000, null=True, upload_to='carrier/insurance-card-photo-front/')),
                ('insurance_card_photo_back', models.ImageField(blank=True, max_length=1000, null=True, upload_to='carrier/insurance-card-photo-back/')),
                ('additional_insurance_cards', models.ImageField(blank=True, max_length=1000, null=True, upload_to='carrier/additional-insurance-cards/')),
                ('consent_recording', models.FileField(blank=True, max_length=1000, null=True, upload_to='carrier/consent-recording/')),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.today, null=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('user_promo_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Promo code of the agent who created this record.')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Agent', verbose_name='Agent name')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Manager', verbose_name='Manager name')),
                ('status', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Status', verbose_name='Status')),
                ('type_of_test', models.ForeignKey(blank=True, max_length=250, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Test_choices', verbose_name='Test choices')),
            ],
            options={
                'ordering': ['patient_name'],
            },
        ),
    ]
