# Generated by Django 2.1.4 on 2018-12-17 08:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='date_app_rec',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 17), null=True, verbose_name='Date application recorded'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='date_bioconfim_rec_app',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 17), null=True, verbose_name='Date bioconfirm recorded application'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='date_of_qca',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 17), null=True, verbose_name='Date of QCA'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='date_paid',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 17), null=True, verbose_name='Date paid'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='date_sample_rec',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 17), null=True, verbose_name='Date sample recorded'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='date_submitted_to_telemed',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 17), null=True, verbose_name='Date submitted to telemed'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='date_telemed_returned',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 17), null=True, verbose_name='Date telemed returned'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='rejection_date',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 17), null=True, verbose_name='Rejection Date'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='submitted_to_tamika_ins_verifier',
            field=models.DateField(blank=True, default=datetime.date(2018, 12, 17), null=True, verbose_name='Date submitted to Tamika ins verifier'),
        ),
    ]
