# Generated by Django 2.1.5 on 2019-01-23 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0004_carrier_for_carrier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='status',
            field=models.CharField(blank=True, choices=[(1, 'CGX/CGD'), (2, 'DUPLICATE'), (3, 'HOLD'), (4, 'MISSING INFORMATION'), (5, 'REJECTED'), (6, 'WRONG APPLICATION'), (7, 'Resubmit from Elite'), (8, 'RESIGNED'), (10, 'REJECTED - HMO'), (11, 'REJECTED - NO ID'), (12, 'REJECTED - INELIGIBLE'), (13, 'REJECTED - INACTIVE'), (14, 'Higd ded 6680.37'), (15, 'REJECTED - CARESOURCE')], max_length=100, null=True, verbose_name='Status'),
        ),
    ]
