# Generated by Django 2.1.5 on 2019-01-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0005_auto_20190123_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='status',
            field=models.CharField(blank=True, choices=[('CGX/CGD', 'CGX/CGD'), ('DUPLICATE', 'DUPLICATE'), ('HOLD', 'HOLD'), ('MISSING INFORMATION', 'MISSING INFORMATION'), ('REJECTED', 'REJECTED'), ('WRONG APPLICATION', 'WRONG APPLICATION'), ('Resubmit from Elite', 'Resubmit from Elite'), ('RESIGNED', 'RESIGNED'), ('REJECTED - HMO', 'REJECTED - HMO'), ('REJECTED - NO ID', 'REJECTED - NO ID'), ('REJECTED - INELIGIBLE', 'REJECTED - INELIGIBLE'), ('REJECTED - INACTIVE', 'REJECTED - INACTIVE'), ('Higd ded 6680.37', 'Higd ded 6680.37'), ('REJECTED - CARESOURCE', 'REJECTED - CARESOURCE')], max_length=100, null=True, verbose_name='Status'),
        ),
    ]
