# Generated by Django 2.1.5 on 2019-01-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0006_auto_20190123_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='month',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
