# Generated by Django 2.1.4 on 2019-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0008_remove_carrier_for_carrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='additional_insurance_cards',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='carrier/additional-insurance-cards/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='insurance_card_photo_back',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='carrier/insurance-card-photo-back/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='insurance_card_photo_front',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='carrier/insurance-card-photo-front/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='carrier',
            name='patient_id_photo',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='bio-confirm-master/patient-id-photo/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='type_of_test',
            field=models.CharField(blank=True, choices=[('CARRIER', 'CARRIER'), ('CGX', 'CGX'), ('CGX/CARRIER', 'CGX/CARRIER'), ('L', 'L')], max_length=100, null=True, verbose_name='Test choices'),
        ),
    ]
