# Generated by Django 2.1.4 on 2019-02-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0015_auto_20190219_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='patient_name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Patient Name'),
        ),
    ]
