# Generated by Django 2.1.4 on 2019-03-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrier', '0018_updates_test_and_status_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='date_bioconfim_rec_app',
            field=models.DateField(blank=True, null=True, verbose_name='Date bioconfirm recorded application'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='date_of_qca',
            field=models.DateField(blank=True, null=True, verbose_name='Date of QCA'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='date_paid',
            field=models.DateField(blank=True, null=True, verbose_name='Date paid'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='date_sample_rec',
            field=models.DateField(blank=True, null=True, verbose_name='Date sample recorded'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='date_submitted_to_telemed',
            field=models.DateField(blank=True, null=True, verbose_name='Date submitted to telemed'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='date_telemed_returned',
            field=models.DateField(blank=True, null=True, verbose_name='Date telemed returned'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='rejection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Rejection Date'),
        ),
    ]
