# Generated by Django 2.1.4 on 2018-12-15 12:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cgx', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DME',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_id', models.CharField(max_length=250, verbose_name='Agent ID Number')),
                ('patient_id', models.CharField(blank=True, max_length=250, null=True, verbose_name='Patient ID Number')),
                ('date', models.DateField(blank=True, default=datetime.date(2018, 12, 15), null=True, verbose_name='Date')),
                ('sent_to_telemed', models.CharField(blank=True, max_length=250, null=True, verbose_name='Sent to Telemed')),
                ('patient_status', models.CharField(blank=True, choices=[(1, 'PPO S+S Checking'), (2, 'Sent to CGS Check'), (3, 'Sent to PPO Check'), (4, 'Sent to DME'), (5, 'Sent to Telemed')], max_length=2, null=True)),
                ('date_returned_for_refiling_with_remn', models.DateField(blank=True, null=True, verbose_name=datetime.date(2018, 12, 15))),
                ('eligibility_verified', models.CharField(blank=True, max_length=250, null=True, verbose_name='Eligibility Verified')),
                ('patient_first_name', models.CharField(blank=True, max_length=250, null=True, verbose_name="Patient's First Name")),
                ('patient_last_name', models.CharField(blank=True, max_length=250, null=True, verbose_name="Patient's Last Name")),
                ('primary_insurance_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Primary Insurance Name')),
                ('braces_requested', models.CharField(blank=True, max_length=250, null=True, verbose_name='Braces Requested')),
                ('braces_s_plus_s_approved', models.CharField(blank=True, max_length=250, null=True, verbose_name='Braces S+S approved')),
                ('braces_shipped', models.CharField(blank=True, max_length=250, null=True, verbose_name='Braces Shipped')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(default=datetime.date(2018, 12, 15), verbose_name='Created date of these informations')),
                ('updated_at', models.DateField(verbose_name='Date updated')),
                ('who_updated', models.CharField(max_length=150, verbose_name='User who updated these informations')),
                ('manager_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cgx.Manager', verbose_name='Manager Name')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
