# Generated by Django 2.1.4 on 2019-03-06 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dme_ii',
            name='consent_recording',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to='dme/consent-recording/'),
        ),
    ]
