# Generated by Django 2.1.4 on 2018-12-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0003_auto_20181218_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dme',
            options={'ordering': ['-date'], 'verbose_name': 'DME', 'verbose_name_plural': 'DME'},
        ),
    ]
