# Generated by Django 2.1.5 on 2019-01-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0005_dme_ii'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dme_ii',
            old_name='ppo_information',
            new_name='ppo_information_ppo_name',
        ),
        migrations.AddField(
            model_name='dme_ii',
            name='ppo_information_mem_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='PPO Information(If not straight from Medicare)(Member ID#)'),
        ),
    ]
