# Generated by Django 2.1.5 on 2019-01-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0006_auto_20190111_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dme_ii',
            name='insurance_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
