# Generated by Django 2.1.5 on 2019-01-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0007_auto_20190111_0419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dme_ii',
            options={'ordering': ['submission_date'], 'verbose_name': 'DME II', 'verbose_name_plural': 'DME II'},
        ),
        migrations.RemoveField(
            model_name='dme_ii',
            name='insurance_card',
        ),
        migrations.RemoveField(
            model_name='dme_ii',
            name='insurance_card_photo',
        ),
        migrations.AddField(
            model_name='dme_ii',
            name='insurance_card_photo_back',
            field=models.ImageField(blank=True, null=True, upload_to='media/card_photo', verbose_name='Insurance Card Photo(Back)'),
        ),
        migrations.AddField(
            model_name='dme_ii',
            name='insurance_card_photo_front',
            field=models.ImageField(blank=True, null=True, upload_to='media/card_photo', verbose_name='Insurance Card Photo(Front)'),
        ),
        migrations.AlterField(
            model_name='dme_ii',
            name='additional_insurance_cards',
            field=models.ImageField(blank=True, null=True, upload_to='media/additional_card_photo/'),
        ),
        migrations.AlterField(
            model_name='dme_ii',
            name='consent_recording',
            field=models.FileField(blank=True, null=True, upload_to='media/consent_recording/'),
        ),
        migrations.AlterField(
            model_name='dme_ii',
            name='patient_id_photo',
            field=models.ImageField(upload_to='media/photo_id/', verbose_name='Patient ID Photo'),
        ),
    ]
