# Generated by Django 2.1.5 on 2019-01-14 10:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0010_auto_20190111_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dme',
            name='date_returned_for_refiling_with_remn',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date returned for refiling with Remn'),
        ),
    ]
