# Generated by Django 2.1.5 on 2019-01-23 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0011_auto_20190114_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='dme_ii',
            name='for_dme',
            field=models.BooleanField(default=0, verbose_name='For DME?'),
        ),
    ]
