# Generated by Django 2.1.5 on 2019-01-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0012_dme_ii_for_dme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dme',
            name='manager_name',
        ),
        migrations.AlterField(
            model_name='dme_ii',
            name='patient_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='photo_id/', verbose_name='Patient ID Photo'),
        ),
        migrations.DeleteModel(
            name='DME',
        ),
    ]
