# Generated by Django 2.1.5 on 2019-01-25 07:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0013_auto_20190123_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dme_ii',
            name='submission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
