# Generated by Django 2.1.5 on 2019-01-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0014_auto_20190125_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dme_ii',
            name='for_dme',
        ),
    ]
