# Generated by Django 2.1.4 on 2019-01-31 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0015_remove_dme_ii_for_dme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dme_ii',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
    ]
