# Generated by Django 2.1.4 on 2019-01-31 09:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0016_auto_20190131_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dme_ii',
            name='submission_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
