# Generated by Django 2.1.4 on 2019-02-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0018_auto_20190201_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dme_ii',
            name='additional_insurance_cards',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='dme/additional-card-photo/'),
        ),
        migrations.AlterField(
            model_name='dme_ii',
            name='consent_recording',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='dme/consent-recording/'),
        ),
        migrations.AlterField(
            model_name='dme_ii',
            name='insurance_card_photo_back',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='dme/insurance-card-photo-back/', verbose_name='Insurance Card Photo(Back)'),
        ),
        migrations.AlterField(
            model_name='dme_ii',
            name='insurance_card_photo_front',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='dme/insurance-card-photo-front/', verbose_name='Insurance Card Photo(Front)'),
        ),
        migrations.AlterField(
            model_name='dme_ii',
            name='patient_id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='dme/patient-id-photo/', verbose_name='Patient ID Photo'),
        ),
    ]
