# Generated by Django 2.1.4 on 2019-02-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0019_auto_20190201_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dme_ii',
            options={'ordering': ['-submission_date'], 'verbose_name': 'DME II', 'verbose_name_plural': 'DME II'},
        ),
    ]
