# Generated by Django 2.1.4 on 2019-02-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0023_dme_ii_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dme_ii',
            name='user_promo_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Promo code of the agent who created this record.'),
        ),
    ]
