# Generated by Django 2.1.4 on 2019-02-21 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dme', '0024_auto_20190219_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dme_ii',
            old_name='localtion_of_wrist_pain',
            new_name='location_of_wrist_pain',
        ),
    ]
