# Generated by Django 2.1.4 on 2019-02-22 08:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sale_rep_name', models.CharField(blank=True, default='n/a', max_length=250, null=True)),
                ('sale_rep_number', models.CharField(blank=True, default='n/a', max_length=250, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('shipping_labels_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True)),
                ('shipping_labels_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True)),
                ('shipping_boxes_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Boxes Quantity Req')),
                ('shipping_boxes_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Boxes Quantyty Auth')),
                ('shipping_bags_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True)),
                ('shipping_bags_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True)),
                ('specimen_bags_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True)),
                ('specimen_bags_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True)),
                ('tox_cups_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Cups Quantity Req')),
                ('tox_cups_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tox Cups Quanty Auth')),
                ('tox_req_forms_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tox Req. Forms Qty Req.')),
                ('tox_req_forms_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tox Req. Forms Qty Auth.')),
                ('pgx_swabs_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='PGX Swabs Qty Req.')),
                ('pgx_swabs_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='PGX Swabs Qty Auth.')),
                ('pgx_swabs_req_forms_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='PGX Swabs Req. Forms Qty Req.')),
                ('pgx_swabs_req_forms_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='PGX Swabs Req. Forms Qty Auth.')),
                ('pgx_medical_necessity_forms_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='PGX Swabs Medical Necessity Forms Qty Req.')),
                ('pgx_medical_necessity_forms_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='PGX Swabs Medical Necessity Forms Qty Auth.')),
                ('cgx_swabs_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='CGX Swabs Qty Req')),
                ('cgx_req_forms_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='CGX Req. Forms Qty Req.')),
                ('tubes_tiger_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tubes Tiger Qty Req.')),
                ('tubes_tiger_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tubes Tiger Qty Auth.')),
                ('tubes_lavender_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tubes Lavender Qty Req.')),
                ('tubes_lavender_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tubes Lavender Qty Auth.')),
                ('tubes_red_top_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tubes Red Top Qty Req.')),
                ('tubes_red_top_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tubes Red Top Qty Auth.')),
                ('tubes_blue_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tubes Blue Qty Req.')),
                ('tubes_blue_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tubes Blue Qty Auth.')),
                ('tubes_dark_blue_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tubes Dark Blue Qty Req.')),
                ('tubes_dark_blue_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tubes Dark Blue Qty Auth.')),
                ('tubes_violet_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tubes Violet Qty Req.')),
                ('tubes_violet_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tubes Violet Qty Auth.')),
                ('straight_needle_18_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Straight Needle(18 Gauge) Qty Req')),
                ('straight_needle_18_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Straight Needle(18 Gauge) Qty Auth')),
                ('straight_needle_20_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Straight Needle(20 Gauge) Qty Req')),
                ('straight_needle_20_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Straight Needle(20 Gauge) Qty Auth')),
                ('straight_needle_21_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Straight Needle(21 Gauge) Qty Req')),
                ('straight_needle_21_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Straight Needle(21 Gauge) Qty Auth')),
                ('straight_needle_22_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Straight Needle(22 Gauge) Qty Req')),
                ('straight_needle_22_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Straight Needle(22 Gauge) Qty Auth')),
                ('straight_needle_23_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Straight Needle(23 Gauge) Qty Req')),
                ('straight_needle_23_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Straight Needle(23 Gauge) Qty Auth')),
                ('butterfly_needle_18_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Butterfly Needle(18 Gauge) Qty Req')),
                ('butterfly_needle_18_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Butterfly Needle(18 Gauge) Qty Auth')),
                ('butterfly_needle_20_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Butterfly Needle(20 Gauge) Qty Req')),
                ('butterfly_needle_20_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Butterfly Needle(20 Gauge) Qty Auth')),
                ('butterfly_needle_21_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Butterfly Needle(21 Gauge) Qty Req')),
                ('butterfly_needle_21_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Butterfly Needle(21 Gauge) Qty Auth')),
                ('butterfly_needle_22_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Butterfly Needle(22 Gauge) Qty Req')),
                ('butterfly_needle_22_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Butterfly Needle(22 Gauge) Qty Auth')),
                ('butterfly_needle_23_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Butterfly Needle(23 Gauge) Qty Req')),
                ('butterfly_needle_23_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Butterfly Needle(23 Gauge) Qty Auth')),
                ('needle_vacuum_tubes_18_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Need Vacuum Tubes Qty Req')),
                ('needle_vacuum_tubes_18_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Need Vacuum Tubes Qty Auth')),
                ('uti_cups_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='UTI Cups Qty Req.')),
                ('uti_cups_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='UTI Cups Qty Auth.')),
                ('uti_urine_tubes_qty_req', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='UTI Urine Tubes Qty Req.')),
                ('uti_urine_tubes_qty_auth', models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='UTI Urine Tubes Qty Auth.')),
                ('culture_swabs', models.CharField(blank=True, default='n/a', max_length=250, null=True)),
                ('tourniquets', models.CharField(blank=True, default='n/a', max_length=250, null=True)),
                ('gauze', models.CharField(blank=True, default='n/a', max_length=250, null=True)),
                ('bandages', models.CharField(blank=True, default='n/a', max_length=250, null=True)),
                ('gel_pack', models.CharField(blank=True, default='n/a', max_length=250, null=True)),
            ],
            options={
                'ordering': ['sale_rep_name'],
            },
        ),
    ]
