# Generated by Django 2.1.4 on 2019-02-22 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['sale_rep_name'], 'verbose_name': 'Supply', 'verbose_name_plural': 'Supplies'},
        ),
        migrations.AddField(
            model_name='supply',
            name='cgx_swabs_qty_auth',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='CGX Swabs Qty Auth'),
        ),
    ]
