# Generated by Django 2.1.4 on 2019-02-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0002_auto_20190222_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='cgx_req_forms_qty_auth',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='CGX Req. Forms Qty Auth.'),
        ),
    ]
