# Generated by Django 2.1.4 on 2019-02-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_supply_cgx_req_forms_qty_auth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supply',
            name='bandages',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='culture_swabs',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='gauze',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='gel_pack',
        ),
        migrations.RemoveField(
            model_name='supply',
            name='tourniquets',
        ),
        migrations.AddField(
            model_name='supply',
            name='bandages_qty_auth',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Bandages Qty Auth'),
        ),
        migrations.AddField(
            model_name='supply',
            name='bandages_qty_req',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Bandages Qty Req'),
        ),
        migrations.AddField(
            model_name='supply',
            name='culture_swabs_qty_auth',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Culture Swabs Qty Auth'),
        ),
        migrations.AddField(
            model_name='supply',
            name='culture_swabs_qty_req',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Culture Swabs Qty Req'),
        ),
        migrations.AddField(
            model_name='supply',
            name='gauze_qty_auth',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Gauze Qty Auth'),
        ),
        migrations.AddField(
            model_name='supply',
            name='gauze_qty_req',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Gauze Qty Req'),
        ),
        migrations.AddField(
            model_name='supply',
            name='gel_pack_qty_auth',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Gel Pack Qty Auth'),
        ),
        migrations.AddField(
            model_name='supply',
            name='gel_pack_qty_req',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Gel Pack Qty Req'),
        ),
        migrations.AddField(
            model_name='supply',
            name='tourniquets_qty_req',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tourniquets Qty Auth'),
        ),
    ]
