# Generated by Django 2.1.4 on 2019-02-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0004_auto_20190222_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='tourniquets_qty_auth',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tourniquets Qty Auth'),
        ),
        migrations.AlterField(
            model_name='supply',
            name='tourniquets_qty_req',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True, verbose_name='Tourniquets Qty Req'),
        ),
    ]
