# Generated by Django 2.1.4 on 2019-02-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0005_auto_20190222_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='supply',
            name='company_name',
            field=models.CharField(blank=True, default='n/a', max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='supply',
            name='status',
            field=models.CharField(blank=True, choices=[('ACCCEPTED', 'Accepted'), ('NOT ACCEPTED', 'Not Accepted')], max_length=100, null=True),
        ),
    ]
